version: 2
updates:
  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
    open-pull-requests-limit: 5
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "fix(deps)"
      include: "scope"

  # Maintain NPM Actions
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
    commit-message:
      prefix: "fix(deps)"
      include: "scope"