name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Setup GitHub Pages Infrastructure
        uses: actions/configure-pages@v6

      - name: Restore Next.js Cache
        uses: actions/cache@v5
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and Export Static Site
        run: pnpm run build

      - name: Upload Static Export Artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./out # Next.js static output directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
